name: psifos_mobile_crypto
description: Psifos crypto for Psifos Mobile.
version: 0.0.1

environment:
  sdk: '>=3.1.1 <4.0.0'

dependencies:
  pointycastle: ^3.7.3
  convert: ^3.1.1

dev_dependencies:
  test: ^1.24.9


